### ISSUE TITLE
Feature Proposal: Add variety to chord generation

### ISSUE THREAD

**Issue by mickmister** [scribbletune/scribbletune#110]
I want to be able to tell Scribbletune "Play C Major in several octaves", and it generate a chord full of notes that would be played with both hands on a piano. Something like "c3 g3 c4 c5 e5 g5" for the notes.

There could be a variety of options to configure

- Just octaves and fifths in the bass
- Just notes in the higher register
- Both registers (like the CM chord above)
- Standard Triad - I think this is the only option at the moment

This way you can command multiple midi tracks to do different styles of things, including using the arp feature on some of them.

In order to make the result more random, we can do different inversions, with a variable result. For example, given the same params we could generate "c3 g3 c4 g4 c5 e5", which will sound a bit different than the chord at the top of this description.

To make chord transitions sound more natural, it can be beneficial to have notes/octaves not drastically change, so something like CM "c4 e4 g4 c5" and FM "c4 f4 a4 c5" may sound better than "f4 a4 c5 f5" for the FM chord.

What do you think of this feature being added to the library? I'd like to implement it, if it's well-received.

P.S. This library is awesome!!

**Comment by walmik** [comment]
Hello @mickmister 

Thank you for trying out this library and going over it in detail to the extent that you have such nice suggestions on improving it :)

I really like this idea. Would love to see your recommendation for it's interface. As you may have already noted, Scribbletune follows a very minimal, declarative API [midi generation or even browser based performance can get messy quickly if the API is not minimal]. At the moment you can get chords in 2 ways in Scribbletune (and this works for both MIDI as well as browser):

- A method that returns chord notes as an array: `chord('CM')`
- Define a chord right in the `notes` param of the `clip` method: `notes: 'CM Em GM'`

Both of these allow passing the octave that you d like to get the chord(s) in:
- `chord('CM-4')`
- `notes: 'CM-4 Em-5 GM-3'`

A great interface would be to be able to do the above and yet manage to have inversions or a range of octaves or a custom variation. I believe this is the real challenge. To meet this challenge it's ok to take liberty in terms of the pattern in which chords are defined.

To take an example, Before `R` and `[]` was introduced, the pattern language in Scribbletune only consisted of `x`, `-` and `_`. Extending this pattern language with additional characters allowed for additional functionality. Namely Random notes (or velocities) via `R` and sub division of patterns at various points and subdivisions via `[` and `]`.

If we can have some extension of the still quite unexplored chord pattern in Scribbletune to accomodate the fantastic feature you suggested, then we can have a backward compatible, suddenly much more musical, feature added to Scribbletune.

For example, if `CM` returns `c4 e4 g4` (octave 4 is default because of [middle C](https://medium.com/@_walmik/middle-c-5c948bd27b6e)) and `CM-3` returns `c3 e3 g3`, how about `CM-3_5` returns `c3 e3 g3 c4 e4 g4 c5 e5 g5` to denote a range and `CM-3+5` returns `c3 e3 g3 c5 e5 g5` to denotes 2 specific octaves.

Of course this only addresses the third bullet point from your list, but hopefully it gives some clarity on what I mean by a minimal API. Basically users shouldnt need to call any additional method or argument in order to achieve the advanced chord variation. Hope this helps! I look forward to this feature :)

**Comment by mickmister** [comment]
@walmik Thanks for the great explanation! This gives me enough direction to get started on this.

If you're up for it, I'd like to discuss with you more of what I plan to do with the library, outside the scope of this ticket. Mainly to figure out what should be in the library, and what should be in my application layer. If you're up for it, I can send you an invite to my chat server to move conversation that is unrelated to the ticket over there. Let me know what you think!

**Comment by walmik** [comment]
Oh yes by all means! Sorry for the delay in responding here. My email is my first name dot last name at gmail ;)

**Comment by qchenevier** [comment]
@mickmister @walmik what do you think of opening a chat (discord, slack, google chat...) to discuss improvements for a scribbletune v4 ? I'm also willing to propose features and contribute PRs.

**Comment by mickmister** [comment]
@qchenevier For sure! I'll leave it up to you guys since I'm the newcomer :)

**Comment by qchenevier** [comment]
I just discovered that GitHub has a talk discussion feature since a few years: https://help.github.com/en/github/building-a-strong-community/about-team-discussions

We only need to start a "public discussion" to discuss.

@walmik are you able to create a public discussion in scribbletune organization ?

**Comment by walmik** [comment]
I created a team and invited the both of you 👍
