### ISSUE TITLE
Duration from pattern

### ISSUE THREAD

**Issue by healzer** [scribbletune/scribbletune#99]
Is it possible to dynamically determine the duration given a pattern?
Let's say I have a pattern like `xx[x[RR]][x[RR]]`
how can we determine how many "half notes" this sequence consists of?

This is important for me to determine when to schedule the next pattern to play; since I cannot find any "on finished playback" events in ToneJS.

**Comment by walmik** [comment]
Hi @healzer 

Apologies for the delay in responding here. I d like to learn more bout the problem you re trying to solve. Do you want to know this duration so that you can play the next clip in correct time? If so then I had faced this when I had put together a [browser based Live application](https://github.com/scribbletune/live) for a demo and hence added the method here https://github.com/scribbletune/scribbletune/blob/master/src/channel.ts#L3-L16

If your reasons were different then I d imagine some function could be written to derive the number of half notes from a pattern. You d also need to provide it the "subdiv" used (that s scribbletune's word for note length). Like Tone.js, Scribbletune uses quarter notes as a default value for each non subdivided x, but it can be bypassed with other values. In other words you d need to only calculate it for the subdivided part of the pattern (which is between square braces). Some amount of recursion could go into this. I have a similar functionality that you could use as reference: https://github.com/scribbletune/scribbletune/blob/master/src/clip.ts#L115-L170

**Comment by healzer** [comment]
> 
> 
> Hi @healzer
> 
> Apologies for the delay in responding here. I d like to learn more bout the problem you re trying to solve. Do you want to know this duration so that you can play the next clip in correct time? If so then I had faced this when I had put together a [browser based Live application](https://github.com/scribbletune/live) for a demo and hence added the method here https://github.com/scribbletune/scribbletune/blob/master/src/channel.ts#L3-L16
> 
> If your reasons were different then I d imagine some function could be written to derive the number of half notes from a pattern. You d also need to provide it the "subdiv" used (that s scribbletune's word for note length). Like Tone.js, Scribbletune uses quarter notes as a default value for each non subdivided x, but it can be bypassed with other values. In other words you d need to only calculate it for the subdivided part of the pattern (which is between square braces). Some amount of recursion could go into this. I have a similar functionality that you could use as reference: https://github.com/scribbletune/scribbletune/blob/master/src/clip.ts#L115-L170

Thanks for responding :)
Yes it's for a live web app as well. I solved it by manually keeping track of the duration (using the notes' notation).

**Comment by walmik** [comment]
Thanks @healzer for closing the issue. In case you want some more ideas (from implementation point of view) then i had given a talk at Github last year where i more or less build a web app with React, GraphQL (via Apollo) and ofc Tone.js and Scribbletune. The code is open sourced and maybe you can refer to it if you hit some common pitfalls https://www.youtube.com/watch?v=G1bRi4El0iw
